apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: dev-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
        class: standard
  template:
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/name
                    operator: In
                    values:
                      - dev-cluster
              topologyKey: "kubernetes.io/hostname"
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: dev-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.0
    metadataVersion: 3.7-IV4
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      # - name: external
      #   port: 9094
      #   type: nodeport
      #   tls: false
    resources:
      requests:
        memory: 1Gi
        cpu: 512m
      limits:
        memory: 1Gi
        cpu: "1"
    logging: 
      type: inline
      loggers:
        log4j.logger.io.strimzi: "DEBUG"
        log4j.logger.kafka: "DEBUG"
        log4j.logger.org.apache.kafka: "DEBUG"
    config:
      auto.create.topics.enable: true
      delete.topic.enable: true
      num.partitions: 24
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      min.insync.replicas: 2
      group.initial.rebalance.delay.ms: 0
      log.retention.hours: 336
      log.roll.hours: 336
      log.retention.bytes: -1
      sasl.enabled.mechanisms: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512,OAUTHBEARER
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-kraft-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
# ---

# apiVersion: kafka.strimzi.io/v1beta2
# kind: KafkaTopic
# metadata:
#   name: my-topic
#   labels:
#     strimzi.io/cluster: dev-cluster
# spec:
#   partitions: 24
#   replicas: 3
#   config:
#     segment.bytes: 1073741824
#     retention.ms: 2592000000
#     segment.ms: 2592000000